// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cg_bot.Database;

namespace cg_bot.Migrations
{
    [DbContext(typeof(CgBotContext))]
    partial class CgBotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("cg_bot.Database.Entities.CallOfDutyPlayerDataEntity", b =>
                {
                    b.Property<ulong>("ServerID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameAbbrev")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeAbbrev")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalKills")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalWins")
                        .HasColumnType("REAL");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<double>("WeeklyKills")
                        .HasColumnType("REAL");

                    b.HasKey("ServerID", "DiscordID", "GameAbbrev", "ModeAbbrev");

                    b.ToTable("CallOfDutyPlayerDataEntity");
                });

            modelBuilder.Entity("cg_bot.Database.Entities.ServersEntity", b =>
                {
                    b.Property<ulong>("ServerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("AdminRoleID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowServerPermissionBlackOpsColdWarTracking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowServerPermissionModernWarfareTracking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowServerPermissionSoundpadCommands")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowServerPermissionWarzoneTracking")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("BlackOpsColdWarKillsRoleID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("CallOfDutyNotificationChannelID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ModernWarfareKillsRoleID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrefixUsed")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("SoundboardNotificationChannelID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ToggleBlackOpsColdWarTracking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ToggleModernWarfareTracking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ToggleSoundpadCommands")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ToggleWarzoneTracking")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("WarzoneKillsRoleID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("WarzoneWinsRoleID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ServerID");

                    b.ToTable("ServersEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
